### ISSUE TITLE
[Windows] Shortcuts fail to sync to native helper - type mismatch (number vs string)

### ISSUE THREAD

**Issue by shunta-if** [amicalhq/amical#102]
## Bug Description

After updating from v0.1.17 to v1.0.0 on Windows 11, keyboard shortcuts (Push to Talk, etc.) no longer work and cannot be reconfigured. The UI shows `e.toUpperCase is not a function` error when trying to set new shortcuts.

## Root Cause

The Electron app (v1.0.0) sends shortcut keycodes as **numbers** (e.g., `[162, 91]` for Ctrl+Win) to the WindowsHelper.exe via the native bridge, but the C# WindowsHelper still expects **strings** (e.g., `["Ctrl", "Win"]`).

### Evidence from logs (`amical.log`):

```
[RpcHandler] Error in setShortcuts: The JSON value could not be converted to System.String.
Path: $.pushToTalk[0] | LineNumber: 0 | BytePositionInLine: 18.
```

```
[error] [ (native-bridge)] Failed to sync shortcuts to native helper
```

This error occurs on every app startup after the v0.1.17 → v1.0.0 update.

## Steps to Reproduce

1. Have Amical v0.1.17 installed with working shortcuts (e.g., Ctrl+Win for Push to Talk)
2. Update to v1.0.0
3. Observe that shortcuts no longer work
4. Try to reconfigure shortcuts in Settings → Shortcuts
5. See `e.toUpperCase is not a function` error

## Expected Behavior

Shortcuts should work after the update, and users should be able to reconfigure them.

## Analysis

- Migration v6 (`qC` function in main.js) converts string key names to numeric keycodes in the database — this runs correctly
- The Electron app now uses numeric keycodes internally (e.g., `162` for Ctrl, `91` for Win)
- `syncShortcutsToNative()` sends these numbers directly to WindowsHelper.exe
- WindowsHelper.exe (C#/.NET 8) deserializes `pushToTalk` as `string[]`, causing `System.Text.Json` to throw when it encounters a number instead of a string
- PR #70 fixed keycode mappings for macOS but did not address this Windows-specific type mismatch

## Possible Fix

Either:
1. Update WindowsHelper.exe to accept numeric keycodes (deserialize as `int[]`)
2. Convert numeric keycodes back to string key names before sending to the native bridge in `syncShortcutsToNative()`

## Environment

- OS: Windows 11 Home 10.0.26200
- Amical version: 1.0.0
- Previous version: 0.1.17

**Comment by haritabh-z01** [comment]
@shunta-if this shouldn't break reconfiguration of shortcuts, etc., the only thing that would get impacted if the shortcut sync fails is the key suppression at. I suspect a stale Windows helper binary, etc., to be the cause here.
End to end flow is using numeric values only - https://github.com/amicalhq/amical/blob/main/packages/native-helpers/windows-helper/src/Models/Generated/Models.cs#L297-L298

**Comment by shunta-if** [comment]
Thanks for the quick response!

Unfortunately, it **is** preventing me from re-setting shortcuts. When I try to record a new shortcut in Settings → Shortcuts, I get a `e.toUpperCase is not a function` error in the UI, and the shortcut is not saved.

I believe the WindowsHelper.exe binary bundled with v1.0.0 is outdated and doesn't match the current source code. The source on main defines `List<long>`, but the bundled binary still expects `string` — the log confirms this on every app startup:

```
[RpcHandler] Error in setShortcuts: The JSON value could not be converted to System.String. Path: $.pushToTalk[0] | LineNumber: 0 | BytePositionInLine: 18.
```

So it seems like the WindowsHelper binary just needs to be rebuilt and re-bundled with the next release.

**Comment by haritabh-z01** [comment]
@shunta-if I think the update probably didn't complete properly in your case leaving you with the stale windows helper, you can uninstall and reinstall v1 release, and it should fix the issue for you.

**Comment by shunta-if** [comment]
Reinstalling v1.0.0 fixed the issue — shortcuts are working again now! 🎉

Thanks for the quick help, really appreciate it!
